---
title: "WK9Assignment"
author: "Fomba Kassoh"
date: "2023-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The 

```{r}
library(httr)
library(jsonlite)
library(dplyr)
library(openintro)

# Replace 'YOUR_API_KEY' with the actual API key you obtained.
api_key <- "ABdgPNF8HPZt2yGi7nAr6dhUUE5OxYxp"

# Example queries

# Set your query parameters (you can adjust these as needed).
query_params <- list(
  q = "transportation",
  fq = "source:('The New York Times')",
  begin_date = "20231001", # Start date
  end_date = "20231031",   # End date
  sort = "newest",         # Sorting order
  "api-key" = "c43a50d3-3053-41ce-89f7-66c7ec00886d"
)

# Define the base URL for the Article Search API.
base_url <- paste0("https://api.nytimes.com/svc/search/v2/articlesearch.json?query_params&api-key=", "ABdgPNF8HPZt2yGi7nAr6dhUUE5OxYxp")

response <- GET(base_url)
if (http_type(response) == "application/json") {
  response_text <- content(response, "text", encoding = "UTF-8")
  data <- jsonlite::fromJSON(response_text)
  if ("response" %in% names(data) && "docs" %in% names(data$response)) {
    extracted_data <- data$response$docs
  } else {
    stop("Response JSON structure is not as expected")
  }
} else {
  stop("Invalid response content type. Expected 'application/json'.")
}



json_file <- "nytimes_articles_transp.json"
write_json(data, json_file)




```


#1: Article API

```{r}
# Replace 'YOUR_API_KEY' with the actual API key you obtained.
api_key <- "ABdgPNF8HPZt2yGi7nAr6dhUUE5OxYxp"

# Example queries

# Set your query parameters (you can adjust these as needed).
query_params <- list(
  q = "transportion",
  fq = "source:('The New York Times')",
  fl="-multimedia",
  begin_date = "20231001", # Start date
  end_date = "20231031",   # End date
  sort = "newest",         # Sorting order
  "api-key" = "ABdgPNF8HPZt2yGi7nAr6dhUUE5OxYxp"
)

# Define the base URL for the Article Search API.
base_url <- paste0("https://api.nytimes.com/svc/search/v2/articlesearch.json?query_params&api-key=", "ABdgPNF8HPZt2yGi7nAr6dhUUE5OxYxp")

response <- GET(base_url)
if (http_type(response) == "application/json") {
  response_text <- content(response, "text", encoding = "UTF-8")
  data <- jsonlite::fromJSON(response_text)
  if ("response" %in% names(data) && "docs" %in% names(data$response)) {
    extracted_data <- data$response$docs
  } else {
    stop("Response JSON structure is not as expected")
  }
} else {
  stop("Invalid response content type. Expected 'application/json'.")
}



json_file <- "nytimes_articles_transp.json"
write_json(data, json_file)




```


```{r}
#"C:/Users/RemoteUser/Documents/DATA 607/nytimes_articles_transp.json"
gitJson <-"C:/Users/RemoteUser/Documents/DATA 607/nytimes_articles_transp.json"
FBooksJson <- fromJSON(gitJson, flatten = TRUE)
head(FBooksJson)
```
```{r}
FBooksJson$source
```



```{r, results='asis'}
library(knitr)
kable(FBooksJson)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
